const fs=require('fs'),vm=require('vm');
const store={};
const sb={localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>{store[k]=String(v);}},console,setTimeout,clearTimeout,AbortController,URL,alert:()=>{},showToast:()=>{},showDetail:()=>{},fetch:async()=>({ok:true,status:200,json:async()=>({choices:[{message:{content:'{}'}}]})})};
vm.createContext(sb);
const djs=fs.readFileSync('data.js','utf8').replace('const expressions','globalThis.expressions');
vm.runInContext(djs,sb);
const h=fs.readFileSync('index.html','utf8');
const s1=h.indexOf('<script>')+8, s2=h.lastIndexOf('</script>');
sb.shuffleArr=a=>{const r=a.slice();for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]];}return r;};
sb.topicOf=k=>({icon:'X',name:k});
sb.escapeHtml=s=>(s||'');
const els={};
const mkEl=()=>({innerHTML:'',style:{},textContent:'',value:'',classList:{toggle:()=>{},remove:()=>{},add:()=>{}},addEventListener:()=>{},getAttribute:()=>null});
sb.document={getElementById:id=>{if(!els[id])els[id]=mkEl();return els[id];},querySelectorAll:()=>[],querySelector:()=>null,addEventListener:()=>{}};
sb.genStyle='vlogger';
sb.location={protocol:'http:',hostname:'127.0.0.1'};
vm.runInContext(h.slice(s1,s2).replace('const COURSE_DAILY_UNIT1','globalThis.COURSE_DAILY_UNIT1').replace('const COURSE_DAILY_SKELETONS','globalThis.COURSE_DAILY_SKELETONS'),sb);
const U=sb.COURSE_DAILY_UNIT1;
console.log('0 数据: 场景'+U.scenes.length+'个 维度'+U.dims.length+'个 剧集来源'+U.shows.length+'部');
sb.openUnit(0);
console.log('1 开场页:', els.learnCourse.innerHTML.includes('sc-intro')&&els.learnCourse.innerHTML.includes('开始看第 1 个场景')?'PASS':'FAIL');
console.log('2 开场含剧情说明:', els.learnCourse.innerHTML.includes('从 4 部剧 5 个场景')?'PASS':'FAIL');
sb.renderUnitScene();
const sc1=els.learnCourse.innerHTML;
console.log('3 场景卡:', sc1.includes('sc-card')&&sc1.includes('🎬 情境')?'PASS':'FAIL');
console.log('4 完整对话(双语):', sc1.includes('sc-dialogue')&&sc1.includes('sc-zh')?'PASS':'FAIL');
console.log('5 关键说法高亮:', sc1.includes('sc-hl')&&sc1.includes('It\'s just that')?'PASS':'FAIL');
console.log('6 这句好在哪:', sc1.includes('这句好在哪')?'PASS':'FAIL');
console.log('7 同维度换着说:', sc1.includes('同维度换着说')&&sc1.includes('The thing is')?'PASS':'FAIL');
console.log('8 进度环:', sc1.includes('dlq-ring')?'PASS':'FAIL');
sb.nextScene();
console.log('9 场景2:', els.learnCourse.innerHTML.includes('S01E02')?'PASS':'FAIL');
sb.sceneIdx=U.scenes.length-1; sb.renderUnitScene(); sb.nextScene();
console.log('10 维度观点页:', els.learnCourse.innerHTML.includes('不同维度的观点表达')&&els.learnCourse.innerHTML.includes('软化开场')?'PASS':'FAIL');
console.log('11 三维度:', els.learnCourse.innerHTML.includes('礼貌否定')&&els.learnCourse.innerHTML.includes('先扬后抑')?'PASS':'FAIL');
console.log('12 维度含观点表达:', els.learnCourse.innerHTML.includes('It\'s just that…')&&els.learnCourse.innerHTML.includes('I wouldn\'t say')?'PASS':'FAIL');
sb.finishUnit();
console.log('13 完成页:', els.learnCourse.innerHTML.includes('本关完成')&&els.learnCourse.innerHTML.includes('个维度')?'PASS':'FAIL');
console.log('14 完成度保存:', store['wb_course_unit1']?'PASS':'FAIL');
sb.renderCourseHome();
console.log('15 通关后地图显示已通关:', els.learnCourse.innerHTML.includes('dlg-node done')&&els.learnCourse.innerHTML.includes('已通关')?'PASS':'FAIL');
console.log('16 无做题机制(挖空/排序/选择):', !h.includes('startOrder')&&!h.includes('renderUnitQ')&&!h.includes('answerUnitQuiz')?'PASS':'FAIL');
